#!/usr/bin/env python

import sys
from scli import client

from common import base

client = client.create_client(sys.argv[1])

objs = [base.ObjectID(x) for x in sys.argv[2:]]

client.delete(objs)
print('DELETED')
