#!/usr/bin/env python

from __future__ import unicode_literals, print_function

import sys

from veles.schema import nodeid
from veles.scli import client

client = client.create_client(sys.argv[1])

obj = nodeid.NodeID.from_hex(sys.argv[2])

client.delete(obj)
print('DELETED')
