#!/usr/bin/env python

import argparse
from pprint import pprint

from veles.schema.nodeid import NodeID
from veles.scli import client

parser = argparse.ArgumentParser()
parser.add_argument('server', help='server address')
parser.add_argument('auth_key', help='hex-encoded server auth-key')
parser.add_argument(
    'id', help='hex-encoded id of parent object', nargs='?', default=None)
args = parser.parse_args()

client = client.create_client(args.server, args.auth_key)

if args.id is not None:
    obj = NodeID.from_hex(args.id)
else:
    obj = NodeID.root_id

pprint(client.list(obj))
