#!/usr/bin/env python

import sys

from veles.schema.nodeid import NodeID
from veles.scli import client

client = client.create_client(sys.argv[1], sys.argv[2])

if len(sys.argv) > 3:
	obj = NodeID.from_hex(sys.argv[3])
else:
	obj = NodeID.root_id

import pprint
for x in client.list_sub(obj):
	pprint.pprint(x)
