#!/usr/bin/env python

import sys
from scli import client

from common import base

client = client.create_client(sys.argv[1])

if len(sys.argv) > 2:
	obj = base.ObjectID(sys.argv[2])
else:
	obj = None

import pprint
for x in client.list_sub(obj):
	pprint.pprint(x)
