#!/usr/bin/env python

import sys
from scli.client import UnixClient

client = UnixClient(sys.argv[1])

if len(sys.argv) > 2:
	obj = int(sys.argv[2])
else:
	obj = None

import pprint
for x in client.list_sub(obj):
	pprint.pprint(x)
