#!/usr/bin/env python

import sys
from scli.client import UnixClient

client = UnixClient(sys.argv[1])

with open(sys.argv[2], 'rb') as f:
    data = f.read()

id = client.create(None,
    tags=['blob', 'fileblob'],
    attr={
        'name': sys.argv[2],
    },
    bindata={
        'blob': data,
    }
)
print('CREATED', id)
