#!/usr/bin/env python

from __future__ import unicode_literals, print_function

import sys
from veles.scli import client
from veles.schema.nodeid import NodeID

client = client.create_client(sys.argv[1], sys.argv[2])

with open(sys.argv[3], 'rb') as f:
    data = f.read()

id = client.create(NodeID.root_id,
    tags={'blob', 'blob.stored', 'blob.file'},
    attr={
        'name': sys.argv[3],
        'width': 8,
    },
    bindata={
        'data': data,
    }
)
print('CREATED', id)
