#!/usr/bin/env python3

# Copyright 2017 CodiLime
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import asyncio
import sys
import signal
import importlib

from veles.async_client.conn import AsyncRemoteConnection
from veles.async_client.proto import create_unix_client, create_tcp_client

print('Świtezianka plugin is starting up...')
loop = asyncio.get_event_loop()

host, _, port = sys.argv[1].rpartition(':')
if host == 'UNIX':
    print('Connecting to UNIX server...')
    proto = loop.run_until_complete(create_unix_client(loop, sys.argv[2], port))[1]
else:
    print('Connecting to TCP server...')
    proto = loop.run_until_complete(create_tcp_client(loop, sys.argv[2], host, int(port)))[1]
conn = AsyncRemoteConnection(loop, proto)

print('Loading plugins...')
for pname in sys.argv[3:]:
    print('{}...'.format(pname))
    mod = importlib.import_module('veles.plugins.' + pname)
    conn.register_plugin(mod)

print('Ready.')
try:
    loop.add_signal_handler(signal.SIGINT, loop.stop)
except NotImplementedError:
    pass
loop.run_forever()
print('Goodbye.')

