#!/usr/bin/env python

import sys
from veles.scli import client

from veles.schema.nodeid import NodeID

from veles.proto.blob import query_blob_get_map, query_blob_get_data

client = client.create_client(sys.argv[1])

obj = NodeID.from_hex(sys.argv[2])

import pprint
r = client.query(obj, query_blob_get_map, None)
pprint.pprint(r)
pprint.pprint(client.query(obj, query_blob_get_data, r.map[0]))
