#!/usr/bin/env python

import sys
from scli import client

from common import base

client = client.create_client(sys.argv[1])

obj = base.ObjectID(sys.argv[2])

import pprint
pprint.pprint(client.get(obj))
