#!/usr/bin/env python
import asyncio
import sys
import signal
import asrv.srv
import asrv.proto
import importlib

print('Świtezianka server starting up...')
loop = asyncio.get_event_loop()
print('Opening database.')
srv = asrv.srv.Server(loop, sys.argv[1])
print('Loading plugins.')
for pname in sys.argv[3:]:
    print('{}...'.format(pname))
    mod = importlib.import_module('plugins.' + pname)
    srv.add_local_plugin(mod.Plugin)
print('Starting UNIX server.')
usrv = loop.run_until_complete(asrv.proto.unix_server(srv, sys.argv[2]))
print('Ready.')
loop.add_signal_handler(signal.SIGINT, loop.stop)
loop.run_forever()
print('Goodbye.')
