#!/usr/bin/env python

import sys

from veles.schema import nodeid
from veles.scli import client
from pprint import pprint

client = client.create_client(sys.argv[1], sys.argv[2])
obj = nodeid.NodeID.from_hex(sys.argv[3])
for x in client.get_sub(obj):
	pprint(x)
