#!/usr/bin/env python

import sys
from scli import client
from binascii import a2b_hex

client = client.create_client(sys.argv[1])

obj = a2b_hex(sys.argv[2])

import pprint
for x in client.get_sub(obj):
	pprint.pprint(x)
