#!/usr/bin/env python3

# Copyright 2017 CodiLime
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from veles.dis.isa.falcon import FalconIsa
from veles.data.bindata import BinData
import sys

data = []
for x in sys.argv[1:]:
    data.append(int(x, 16))

from pprint import pprint
pos = 0
while pos < len(data):
    res = FalconIsa().parse(BinData(8, data), 'aaa', pos)
    pprint(res.__dict__)
    pos += res.len
