#!/usr/bin/env python

from __future__ import unicode_literals, print_function
import sys

from veles.scli import client
from veles.schema.nodeid import NodeID

client = client.create_client(sys.argv[1], sys.argv[2])

with open(sys.argv[3], 'rb') as f:
    data = f.read()

id = client.create(NodeID.root_id,
    tags={'blob', 'blob.file', 'blob.stored',},
    attr={
        'name': sys.argv[3],
        'path': sys.argv[3],
        'width': 8,
        'base': 0,
        'size': len(data),
    },
    bindata={
        'data': data,
    }
)
print('CREATED BLOB', id)
h_id = client.create(id,
    pos=(0, None),
    tags={'chunk', 'chunk.stored', 'elf.ehdr',},
    attr={'name': 'elf.ehdr',},
)
print('CREATED HEADER', h_id)
