#!/usr/bin/env python

from __future__ import unicode_literals, print_function

import sys
from veles.scli import client
from veles.schema.nodeid import NodeID

client = client.create_client(sys.argv[1])

with open(sys.argv[2], 'rb') as f:
    data = f.read()

id = client.create(NodeID.root_id,
    tags={'blob', 'fileblob'},
    attr={
        'name': sys.argv[2],
    },
    bindata={
        'blob': data,
    }
)
print('CREATED BLOB', id)
h_id = client.create(id,
    pos=(0, None),
    tags={'chunk', 'elf.ehdr'},
)
print('CREATED HEADER', h_id)
